Ubuntu intro README
FACN8/Pre-course pull request #1
Opened 2019-11-21 12:58 UTC by Karyum

this pull request is still work in progress. the structure of the README is WHAT?WHY?HOW?
in the how i was thinking of having the actual Ubuntu setup on the student's laptop.
and straight after that we have the cli-intro workshop.

is this structure fine for everyone ?

2019-11-21 12:59 UTC, Karyum commented on week1/ubuntu-intro.md
> +- Gives you more power over your computer since it's a lower layer  <!-- help needed -->
i also i need help phrasing this correctly i'm not sure how.

2019-11-21 13:20 UTC, Karyum commented
also thinking about it maybe i should add like a "Further reading" section since we mentioned we wanted like a home work system for the precourse

2019-11-22 15:10 UTC, Karyum commented
TODO: add `Further reading` and `Advanced topics`

2019-11-24 14:00 UTC, shiryz requested changes

2019-11-24 14:00 UTC, shiryz commented on week1/ubuntu-intro.md
> +    - Acer: F2 or DEL
All of these appear on the same line

2019-11-24 14:04 UTC, jamiecoe requested changes

2019-11-24 14:04 UTC, jamiecoe commented on week1/ubuntu-intro.md
> +
I'd suggest that the students review that they've done Step 2 correctly with a mentor before continuing. If they get this step wrong, they could potentially corrupt their hard-drive.

2019-11-24 14:19 UTC, Karyum commented
@shiryz @jamiecoe changes accoring to https://github.com/FACN8/Pre-course/pull/1#pullrequestreview-321963890 https://github.com/FACN8/Pre-course/pull/1#pullrequestreview-321963641 are done

2019-11-25 13:52 UTC, shiryz approved these changes

2019-11-25 14:25 UTC, shiryz commented
@Karyum merge conflicts

2019-11-25 14:31 UTC, jamiecoe approved these changes

2019-11-25 14:31 UTC, merged